### ISSUE TITLE
Spotify Integration ctnd. [3hrs]

### ISSUE THREAD

**Issue by harrismcc** [harrismcc/cs121-team7#10]
- [ ] ensure log in for spotify from user account [1 hour]
- [ ] have the app find top playlist from user [1 hour]
- [ ] research spotify AI [1 hour]

**Stretch**
- [ ] if possible connect app to Spotify AI

**Comment by nickshep** [comment]
I think these may have to be stretch goals for me for this week

**Comment by harrismcc** [comment]
Integrated
