### ISSUE TITLE
Create user logins [3hrs]

### ISSUE THREAD

**Issue by harrismcc** [harrismcc/cs121-team7#4]
We need to have a way for users to login to our app. This means a way to sign up, login, and reject incorrect logins.
	

- [x] **Login Form (Front end)[1.5hrs]**
	- [x] Email [30mins]
		- [x] Reject email already used
		- [x] Reject invalid email address
	- [x] Username [30mins]
		- [x] Reject username already used
	- [x] Password [30mins]
		- [x] Reject insecure password (same as username, too short, etc.)

- [ ] **Login DB (Back End)[1.5hrs]**
	- [x] Research [1hr]
		- [x] Getting started, Firebase documentation
	- [ ] Implementation  [30min]
		- [x] User id field
		- [x] Username field
		- [x] email field
		- [x] hashed password field
		- [ ] Spotify api token field (?)

**Comment by harrismcc** [comment]
Checking in on this, what is the status of those last few checkboxes? Thanks :)

**Comment by nickshep** [comment]
I still have not been able to upload the spotify api token to the database. I also haven't been able to upload the folders. I think I know of a workaround by creating a package but its not ideal.

**Comment by harrismcc** [comment]
Pushing back API token field until task #10 is done
