### ISSUE TITLE
App Flow, Updating UI, Playing Song, Integrating Spotify [8 hours]

### ISSUE THREAD

**Issue by harrismcc** [harrismcc/cs121-team7#7]
For this task, the goal is to be able to click on a song and have it start playing. There are several elements to this:

- [x] Watch tutorial on how to create multiple screens for flow in ReactNative (60 min)
- [x] Set up screen for login and actual app playing zone (60 min)
- [ ] Create dummy playbar at bottom of main screen with play/pause, forward, back (60 min)
- [ ] Create full-screen play view when the playbar is clicked (30 min)
- [ ] Have playbar/playscreen play, pause, and fast forward song (60 min)
- [ ] Have playbar/playscreen display currently playing some name/album art/artist (60 min)
- [ ] Create hardcoded song on main screen to click (60 min)
- [ ] Play hardcoded song when clicked (30 min)
- [x] Watch tutorial on how to integrate Spotify into the application (60 min)

**Comment by nickshep** [comment]
I have not been able to reach these goals this week. I'm stuck on the databases. I think I could probably do these tasks next week.

**Comment by harrismcc** [comment]
Putting a pin in this one as we can't actually play more than 30seconds of a song anyway
