### ISSUE TITLE
Basic App UI [5hrs]

### ISSUE THREAD

**Issue by harrismcc** [harrismcc/cs121-team7#8]
- [x] Change UI to have Login page and a new page for Sign Up [60 min]

- [x] Update error messages so users know what went wrong with their login / sign up attempts [30 min]

- [x] Make UI look cleaner and display a Spotify asset to login with [60 min]

- [x] Enable users to sign in with other apps (not just email) [60 min]

- [x] Set up an email / password reset feature [30 min]

- [x] Make a dummy key entry for where the spotify token would go in the database [60 min]

**Comment by nickshep** [comment]
Have not completed the unchecked boxes. These can be added to next week. I think I might omit the separate page idea or if we want it plan to have that take another 3 hours. I can't figure out the UI elements in JS
